In [6]:
import numpy as np

In [7]:
birthArr = np.loadtxt('data/births.txt',delimiter=',' , dtype=np.int64)
birthArr

array([[   1880,   90993,  110491],
       [   1881,   91954,  100745],
       [   1882,  107850,  113688],
       [   1883,  112321,  104629],
       [   1884,  129022,  114445],
       [   1885,  133055,  107800],
       [   1886,  144535,  110784],
       [   1887,  145982,  101414],
       [   1888,  178627,  120853],
       [   1889,  178366,  110584],
       [   1890,  190377,  111025],
       [   1891,  185482,  101196],
       [   1892,  212346,  122037],
       [   1893,  212906,  112317],
       [   1894,  222922,  115772],
       [   1895,  233630,  117398],
       [   1896,  237920,  119570],
       [   1897,  234202,  112758],
       [   1898,  258770,  122693],
       [   1899,  233023,  106212],
       [   1900,  299828,  150499],
       [   1901,  239348,  106471],
       [   1902,  264077,  122659],
       [   1903,  261973,  119234],
       [   1904,  275371,  128125],
       [   1905,  291629,  132319],
       [   1906,  295303,  133159],
       [   1907,  318566,  1

In [ ]:
#미국에서 태어난 년도, 남아수, 여아수 (1880~2011)

In [5]:
birthArr.shape

(132, 3)

In [16]:
birthArr.mean(axis=0).round(2)

array([   1945.5 , 1225776.07, 1245399.21])

In [17]:
# 1. 남아 ,여아 출생 평균을 구하시요
# y,m,f = birthArr.mean(axis=0)
# print('남아평균',round(m,2) )
# print('여아평균',round(f,2) )
y,m,f = birthArr.mean(axis=0).round(2)
print('남아평균',m )
print('여아평균',f )

남아평균 1225776.07
여아평균 1245399.21


In [25]:
# 2. 2000년대 이후데이터를 구하시요
# 년도   남아   여아
# ==============
# 2000     xx     xx
print('년도','남아','여아',sep='\t')
print('='*30)
for y,m,f in birthArr[ birthArr[:,0] >=2000 ]:
    print(y,m,f)

년도	남아	여아
2000 1814601 1962406
2001 1799049 1941251
2002 1795206 1939815
2003 1825359 1973434
2004 1834145 1982794
2005 1845379 1994841
2006 1898463 2052377
2007 1919408 2072139
2008 1887234 2036289
2009 1832925 1979303
2010 1772738 1913851
2011 1753500 1893230


In [33]:
# 3. 남아출생이 가장많은 년도와 남아수를 구하시요.
mx = birthArr[:,1].max()
for y,m,f in birthArr[ birthArr[:,1] == mx ]:
    print('년도:',y, '남아수:',m)
# birthArr[birthArr[:,1] == 2044160]

년도: 1957 남아수: 2044160


In [ ]:
# 4. 남아출생이 가장많은 top5 를 구하시요(년도와 남아수)
a= np.argsort(birthArr[:,1], axis=0)[:-6:-1]
birthArr[a,:2]

In [39]:
idx = np.argsort( birthArr[:,1] )[:-6:-1]
birthArr[ idx ][:, [0,1] ]

array([[   1957, 2044160],
       [   1959, 2023044],
       [   1960, 2022093],
       [   1961, 2017316],
       [   1958, 2010884]], dtype=int64)

In [ ]:
5. 남아율(%) 을 구하고 각년도별
남아수가 차지하는비율을 데이터로
보여주시요.
남아    여아    남아율
===================
..


In [47]:
m = birthArr[:,1]
w = birthArr[:,2]
ratio = (m/(m+w))*100
print('='*20)
print('남아','여아','남아율',sep='\t')
print('='*20)
for m,w,r in zip(m,w,ratio.round(2)):
    print(m, w, r,sep='\t')

남아	여아	남아율
90993	110491	45.16
91954	100745	47.72
107850	113688	48.68
112321	104629	51.77
129022	114445	52.99
133055	107800	55.24
144535	110784	56.61
145982	101414	59.01
178627	120853	59.65
178366	110584	61.73
190377	111025	63.16
185482	101196	64.7
212346	122037	63.5
212906	112317	65.46
222922	115772	65.82
233630	117398	66.56
237920	119570	66.55
234202	112758	67.5
258770	122693	67.84
233023	106212	68.69
299828	150499	66.58
239348	106471	69.21
264077	122659	68.28
261973	119234	68.72
275371	128125	68.25
291629	132319	68.79
295303	133159	68.92
318566	146833	68.45
334313	154344	68.41
347228	163999	67.92
396501	194218	67.12
418299	225968	64.93
558103	429945	56.49
624518	512557	54.92
761548	654762	53.77
983874	848603	53.69
1044323	890099	53.99
1081280	925511	53.88
1157647	1013537	53.32
1130145	980149	53.55
1198283	1064463	52.96
1232999	1101457	52.82
1200919	1088287	52.46
1206330	1096168	52.39
1248876	1132751	52.44
1217352	1115958	52.17
1185304	1110505	51.63
1192330	1126717	51.41
1153117	110751

In [ ]:
6. 2000년도 이후데이터 에 대해
출생량 을 구하고
남아수가 1800000 이상이면 '많음'아니면 '적음'
이라고 보여 주시요
	남아수 출생량
2000   1233   '많음'
2001   1234   '적음'

In [51]:
birth20 = birthArr[birthArr[:,0] >= 2000]
result = np.where( birth20[:,1] > 1800000, '많음', '적음')

print('='*20)
print('연도','남아수','출생량',sep='\t')
print('='*20)
for a, b, c in zip(birth20[:,0], birth20[:,1], result):
    print(a, b, c, sep='\t')

연도	남아수	출생량
2000	1814601	많음
2001	1799049	적음
2002	1795206	적음
2003	1825359	많음
2004	1834145	많음
2005	1845379	많음
2006	1898463	많음
2007	1919408	많음
2008	1887234	많음
2009	1832925	많음
2010	1772738	적음
2011	1753500	적음


In [ ]:
# 7. 1800년대,1900년대,2000년대 
# 각 남아,여야수 평균을 구하시요

In [61]:
b1800=birthArr[birthArr[:,0]<1900]
b1900=birthArr[ (birthArr[:,0]>=1900) & (birthArr[:,0]<2000)]
b2000=birthArr [birthArr[:,0]>=2000]
y, m ,f = b1800.mean(axis=0)
print( '1800년대','남아평균:',m, '여야평균:',f)
y, m ,f = b1900.mean(axis=0)
print( '1900년대','남아평균:',m, '여야평균:',f)
y, m ,f = b2000.mean(axis=0).round(2)
print( '2000년대','남아평균:',m, '여야평균:',f)

1800년대 남아평균: 176714.15 여야평균: 111820.55
1900년대 남아평균: 1362901.51 여야평균: 1384145.55
2000년대 남아평균: 1831500.58 여야평균: 1978477.5


In [ ]:
# 8. 여아 25%~75%사이의 값을 구하시요
G = birthArr[:,-1]
q25,q75 =np.percentile( G,q=[25,75],axis=0)
G[(G >= q25) & (G <= q75)]