In [1]:
import numpy as np

In [2]:
data = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

2 차원 통계<br>
디폴트 axis=None ==> 1차원의 통계<br>
axis=0 ==>컬럼(열)별 통계값<br>
axis=1 => row(행)별 통계값<br>

In [3]:
# data.sum(axis=None) # np.zum(data, axis=None)
data.sum() # np.sum(data)

52

In [4]:
data.sum(axis=0) #컬럼(열)별 총합  #np,sum(data,axis=0)

array([24, 11, 17])

In [5]:
data.sum(axis=1) #로우(행)별 합계

array([ 6, 14, 19, 13])

In [6]:
data.mean()

4.333333333333333

In [7]:
data.mean(axis=0) #컬럼(열)별 평균

array([6.  , 2.75, 4.25])

In [8]:
data.mean(axis=1) #로우(행)별 평균

array([2.        , 4.66666667, 6.33333333, 4.33333333])

In [9]:
arr = np.array( [2.234,2.123,2.6787] )
arr.round(2)  # 소수점 이하 2자리 반올림

array([2.23, 2.12, 2.68])

In [11]:
data.mean(axis=1).round(2)

array([2.  , 4.67, 6.33, 4.33])

In [12]:
data.max()
# data.min()

10

In [13]:
data.max(axis=0) # 컬럼(열)에서 가장 큰값
# data.min(axis=0) # 컬럼(열)에서 가장 작은값

array([10,  5,  8])

In [14]:
data.max(axis=1) #로우(행)에서 가장 큰값
# data.min(axis=1) # 로우(행)에서 가장 작은값

array([ 3,  7, 10,  6])

In [ ]:
data.std()

In [18]:
data.std(axis=0) # 컬럼(열)의 표준편차
data.std(axis=1) # 로우(행)의 표준편차

array([0.81649658, 2.05480467, 3.8586123 , 1.24721913])

In [15]:
np.median(data)

3.5

In [19]:
np.median(data,axis=0)# 컬럼(열)의 중앙값
np.median(data,axis=1)# 로우(행)의 중앙값

array([6.5, 2.5, 3.5])

In [17]:
np.percentile(data,q=50)

3.5

In [28]:
np.percentile(data,q=[25,50,75],axis=0) # 컬럼(열)의 퍼센테이지 값
# np.percentile(data,q=[25,50,75],axis=1) # 로우(행)의 퍼센테이지 값

array([[4.75, 1.75, 2.75],
       [6.5 , 2.5 , 3.5 ],
       [7.75, 3.5 , 5.  ]])

In [22]:
np.quantile(data,q=0.5)

3.5

In [25]:
np.quantile(data,q=[0.25,0.5,0.75],axis=0)
np.quantile(data,q=[0.25,0.5,0.75],axis=1)

array([[1.5, 3.5, 4.5, 3.5],
       [2. , 5. , 8. , 4. ],
       [2.5, 6. , 9. , 5. ]])

In [26]:
for n in data:  #행단위로 출력
    print(n)

[1 2 3]
[7 5 2]
[10  1  8]
[6 3 4]


In [27]:
for a,b,c in data:  # 행단위로 출력
    print(a,b,c) 

1 2 3
7 5 2
10 1 8
6 3 4
