In [1]:
import numpy as np

In [2]:
arr= np.array( [11,22,33,44,55] )
arr

array([11, 22, 33, 44, 55])

## 1. 인덱싱
- 0 1 2 3 ...
- ... -2 -1

In [3]:
arr[0]

11

In [4]:
arr[-1]

55

### 복수개 선택 인덱싱

In [5]:
arr[[0,2,3]]

array([11, 33, 44])

In [6]:
arr

array([11, 22, 33, 44, 55])

### boolean 인덱싱

In [7]:
arr[[True,False,True,True,False]]

array([11, 33, 44])

## 슬라이싱(sllicing)
- [시작인덱스:끝인덱스:증가치]
- 시작인덱스 <= index < 끝인덱스

In [8]:
arr

array([11, 22, 33, 44, 55])

In [9]:
arr[1:4:1] # 1 <= index < 4      1,2,3

array([22, 33, 44])

In [10]:
arr[1:4:2] # 1 <= index < 4      1,3

array([22, 44])

In [11]:
arr[1:4]  # 증가치 기본은 1

array([22, 33, 44])

In [12]:
arr[:4]  # 시작인덱스 기본값은 0       0 <= index < 4     0,1,2,3

array([11, 22, 33, 44])

In [13]:
arr[1:]  # 1 <= index   1번 인덱스쿠터 끝까지

array([22, 33, 44, 55])

In [14]:
arr[:-1] # 0 <= index < -1

array([11, 22, 33, 44])

In [15]:
arr[-1:-4:-1]  # -1 <= index < -4

array([55, 44, 33])

In [16]:
arr[:-4:-1]  # 디폴트 시작 인덱스 -1

array([55, 44, 33])

In [17]:
arr[::-1]

array([55, 44, 33, 22, 11])

In [20]:
# [44,22]
print(arr[-2::-2])
print(arr[-2:-5:-2])

[44 22]
[44 22]
