In [1]:
import numpy as np

In [18]:
data = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [4]:
data +2 # 요소별 연산

array([[ 3,  4,  5],
       [ 9,  7,  4],
       [12,  3, 10],
       [ 8,  5,  6]])

In [5]:
data*2 # 요소별 연산

array([[ 2,  4,  6],
       [14, 10,  4],
       [20,  2, 16],
       [12,  6,  8]])

In [8]:
data[1] #1행

array([7, 5, 2])

In [9]:
data[1]+2

array([9, 7, 4])

In [10]:
data[1] = 2
data  #1행을 다 2로

array([[ 1,  2,  3],
       [ 2,  2,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [13]:
data[1]=[1,2,3]
data # 1행을 1,2,3으로 수정

array([[ 1,  2,  3],
       [ 1,  2,  3],
       [10,  1,  8],
       [ 6,  3,  4]])

In [16]:
data[1] = data[1]+2
data #1번 행만 +2

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10,  1,  8],
       [ 6,  3,  4]])

In [17]:
data[:,1] = data[:,1]+2
data  # 1번 열만 +2

array([[ 1,  4,  3],
       [ 7, 10,  9],
       [10,  3,  8],
       [ 6,  5,  4]])

## 관계연산자

In [19]:
data = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [22]:
data[:,0]>=5

array([False,  True,  True,  True])

In [21]:
data [data[:,0]>=5] # 0열이 5이상인 행만 출력

array([[ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [23]:
data [data[:,1]>=5] # 1열이 5이상인 행만 출력

array([[7, 5, 2]])

## 논리연산자

In [25]:
data[(data[:,0] == 7) | (data[:,0] == 6)] #0열이 7또는 6인 행 출력

array([[7, 5, 2],
       [6, 3, 4]])