In [2]:
import numpy as np

In [3]:
data = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

## 추가

In [4]:
ax = np.array( [[1,2],[3,4]])
ay = np.array( [[5,6],[7,8]])


In [5]:
# np.append(ax,ay,axis=None) #1으로 출력. 기본값
np.append(ax,ay)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.append(ax,ay,axis=0) # 열에 추가, 행 늘어남

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
np.append(ax,ay,axis=1)  #행에 추가 열늘어님

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [8]:
np.hstack((ax,ay))  #행에 추가, 열 늘어남

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [9]:
np.vstack((ax,ay) ) # 열에 추가, 행 늘어남

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## 삭제

In [11]:
data = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [12]:
np.delete(data, [0,2]) #개별인덱스 삭제

array([ 2,  7,  5,  2, 10,  1,  8,  6,  3,  4])

In [13]:
np.delete(data,[0,2],axis=0) #행인덱스로 삭제

array([[7, 5, 2],
       [6, 3, 4]])

In [14]:
np.delete(data,[0,2],axis=1) #열인덱스로 삭제

array([[2],
       [5],
       [1],
       [3]])

## 수정

In [15]:
data = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [17]:
data[0,0]=2
data

array([[ 2,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [18]:
data[1] = [11,22,33]
data #1행 수정

array([[ 2,  2,  3],
       [11, 22, 33],
       [10,  1,  8],
       [ 6,  3,  4]])

In [19]:
data[:,1] =[1,2,3,4]
data  # 1열 수정

array([[ 2,  1,  3],
       [11,  2, 33],
       [10,  3,  8],
       [ 6,  4,  4]])

## 정렬

In [22]:
data = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [23]:
np.sort(data,axis=None)  # axis=None 이면 1차원으로 풀어서 

array([ 1,  1,  2,  2,  3,  3,  4,  5,  6,  7,  8, 10])

In [24]:
np.sort(data,axis=0)  # 각 열별로 정리

array([[ 1,  1,  2],
       [ 6,  2,  3],
       [ 7,  3,  4],
       [10,  5,  8]])

In [25]:
np.sort(data,axis=1) # 각 행별로 정리

array([[ 1,  2,  3],
       [ 2,  5,  7],
       [ 1,  8, 10],
       [ 3,  4,  6]])

In [26]:
np.sort(data) # 기본값이 행별로 정리.

array([[ 1,  2,  3],
       [ 2,  5,  7],
       [ 1,  8, 10],
       [ 3,  4,  6]])

In [27]:
np.argsort(data, axis=None) #1차원 정렬했을 때 인덱스 값

array([ 0,  7,  1,  5,  2, 10, 11,  4,  9,  3,  8,  6], dtype=int64)

In [28]:
np.argsort(data, axis=0) # 2차원, 열별로 정렬했을 때 인덱스 값

array([[0, 2, 1],
       [3, 0, 0],
       [1, 3, 3],
       [2, 1, 2]], dtype=int64)