In [1]:
import numpy as np

In [2]:
arr= np.array( [11,22,33,44,55] )
arr

array([11, 22, 33, 44, 55])

## 산술, 관계, 논리
- element wise(요소별 연산)

In [3]:
arr+1  #요소별 +1

array([12, 23, 34, 45, 56])

In [4]:
arr*2

array([ 22,  44,  66,  88, 110])

******

아래와 같이 연봉데이터가 있을 때 각 연봉에 대해 세금 3.3을 제한 실수령액을 구하시오.

In [7]:
salary = np.array( [1000,2000,3000,4000,5000])
salary

#1
salary*0.967

array([ 967., 1934., 2901., 3868., 4835.])

In [8]:
#2
salary1 = salary-(salary*0.033) 
salary1


array([ 967., 1934., 2901., 3868., 4835.])

In [9]:
#3
salary-salary*0.033


array([ 967., 1934., 2901., 3868., 4835.])

*********

In [10]:
salary-arr  # 같은 인덱스에서 계산

array([ 989, 1978, 2967, 3956, 4945])

## 관계연산자(<, >, <=, >=, ==, !=)

In [11]:
arr>30

array([False, False,  True,  True,  True])

In [13]:
arr[arr>30]  #boolean인덱싱

array([33, 44, 55])

In [14]:
arr[arr == 44]

array([44])

******

In [26]:
# '철' in '김철수'
nameArr = np.array(['홍길동','김철수','이영철','임꺽정','이황'])
[n for n in nameArr if '철' in n]

['김철수', '이영철']

## 논리연산자(and(&), or(|), not(~))

In [30]:
(arr == 11) | (arr == 33)

array([ True, False,  True, False, False])

In [29]:
arr[ (arr == 11) | (arr == 33) ]

array([11, 33])

In [31]:
(arr > 20) & (arr < 50)

array([False,  True,  True,  True, False])

In [32]:
arr [(arr > 20) & (arr < 50) ]

array([22, 33, 44])

In [33]:
arr[ ~( (arr==11) | (arr==33) ) ]

array([22, 44, 55])

In [34]:
arr [~(arr==33)]

array([11, 22, 44, 55])

In [35]:
arr[arr != 33]

array([11, 22, 44, 55])