In [1]:
import numpy as np

In [17]:
arr= np.array( [11,22,33,44,55] )
arr

array([11, 22, 33, 44, 55])

## 추가

In [10]:
arr = np.append( arr, [66,77] )

In [4]:
arr

array([11, 22, 33, 44, 55, 66, 77])

In [11]:
np.insert(arr,1,[100,200])

array([ 11, 100, 200,  22,  33,  44,  55,  66,  77])

## 수정 : 수정대상 = 수정값

In [12]:
arr[0] = 100
arr

array([100,  22,  33,  44,  55,  66,  77])

In [13]:
arr[-1] = 1000
arr

array([ 100,   22,   33,   44,   55,   66, 1000])

In [14]:
arr [1:4] = 3
arr

array([ 100,    3,    3,    3,   55,   66, 1000])

In [15]:
arr [1:4] = [1,2,3]
arr

array([ 100,    1,    2,    3,   55,   66, 1000])

In [16]:
arr[:3] = arr[:3]+2
arr

array([ 102,    3,    4,    3,   55,   66, 1000])

****

In [ ]:
# 30 이상인 값을 기존의 값에 2를 더한 것으로 수정하시오.
# [11,22,34,46,57]

In [ ]:
arr= np.array( [11,22,33,44,55] )
arr

In [19]:
#1
arr[2:] = arr[2:]+2
arr

array([11, 22, 35, 46, 57])

In [ ]:
#2
arr[arr>=30] = arr[arr>=30]+2

******

## 삭제

In [21]:
arr= np.array( [11,22,33,44,55] )
arr

array([11, 22, 33, 44, 55])

In [22]:
# arr = np.delete(arr,[0,2])
np.delete(arr,[0,2])

array([22, 44, 55])

## where 함수

In [26]:
arr= np.array( [11,22,33,44,55] )
arr

array([11, 22, 33, 44, 55])

In [27]:
np.where(arr<30) # 결과가 참인 index

(array([0, 1], dtype=int64),)

In [28]:
np.where(arr<30,'B','A') # 참이면 B, 거짓이면A

array(['B', 'B', 'A', 'A', 'A'], dtype='<U1')

## select 함수, 조건이 3개 이상인 경우

In [29]:
conList=[arr<30, arr<50, arr>=50]
choiceList = ['C','B','A']
np.select(conList,choiceList)

array(['C', 'C', 'B', 'B', 'A'], dtype='<U11')

In [32]:
arr >= 40

array([False, False, False,  True,  True])

In [31]:
# 40 이상인 데이터를 삭제하세요
#1
np.delete(arr,arr>=40)

array([11, 22, 33])

In [33]:
np.where(arr>=40)

(array([3, 4], dtype=int64),)

In [34]:
#2
arr = np.delete( arr, np.where(arr>=40) )


## 정렬

In [35]:
arr= np.array( [11,22,33,44,55] )
arr

array([11, 22, 33, 44, 55])

In [36]:
arr[0] = 100

In [40]:
np.sort(arr)

array([ 22,  33,  44,  55, 100])

In [38]:
arr1 = np.sort(arr)
arr1[::-1]

array([100,  55,  44,  33,  22])

In [39]:
np.sort(arr)[::-1]

array([100,  55,  44,  33,  22])

In [41]:
# arg ==> index관련 함수
np.argsort(arr) # 개체 오름차순 인덱스 출력

array([1, 2, 3, 4, 0], dtype=int64)

In [42]:
# arr[[1, 2, 3, 4, 0]]  -> 복수개 선택 인덱싱
arr[np.argsort(arr)]

array([ 22,  33,  44,  55, 100])

## 문자열 데이터 검색

In [43]:
nameArr = np.array( ['홍길동', '김철수', '이영철', '임꺽정', '이황'])
nameArr


array(['홍길동', '김철수', '이영철', '임꺽정', '이황'], dtype='<U3')

In [44]:
nameArr[ nameArr=='홍길동' ]

array(['홍길동'], dtype='<U3')

In [45]:
np.char.find( nameArr, '철' )

array([-1,  1,  2, -1, -1])

In [46]:
nameArr[ np.char.find( nameArr, '철' ) >=0 ]

array(['김철수', '이영철'], dtype='<U3')