In [1]:
import numpy as np

In [2]:
arr= np.array( [11,22,33,44,55] )
arr

array([11, 22, 33, 44, 55])

## 1. np의 함수, ndarray객체의 멤버함수

In [3]:
np.sum(arr)

165

In [4]:
arr.sum()

165

In [5]:
np.mean(arr)

33.0

In [6]:
arr.mean()

33.0

In [7]:
np.max(arr)

55

In [8]:
arr.max()

55

In [9]:
np.argmax(arr)

4

In [10]:
arr.argmax() #제일 큰 인덱스

4

In [11]:
arr.min() #np.min(arr)

11

In [12]:
arr.argmin() #np.argmin(arr) #제일 작은 인덱스

0

In [13]:
arr.var() # np.var(arr) #분산

242.0

In [14]:
arr.std() # 표준편차

15.556349186104045

## 2. np의 함수로만 제공

In [15]:
np.median(arr) 
# 중간값: 데이터를 정렬했을 때 가운데값
# 짝수개면 가운데값 2개의 평균
# 홀수개면 가운데값

33.0

In [16]:
arr

array([11, 22, 33, 44, 55])

In [36]:
np.percentile(arr,q=50)

33.0

In [37]:
np.percentile(arr,q=[25,50,75])

array([22., 33., 44.])

In [38]:
np.quantile(arr,q=[0.25,0.5,0.75])

array([22., 33., 44.])

## 연습문제

In [18]:
kor = np.array( [60,55,70,30,20,90])
kor

array([60, 55, 70, 30, 20, 90])

In [ ]:
1. 국어점수가 가장 큰값을 구하시요
2. 국어점수가 80점이상인 값을 구하시요
3. 국어점수가 50점이상 80점이하인 값을 구하시요
4. 국어점수 평균을 구하시요
5. 국어점수 총합을 구하시요.

In [19]:
# 1
kor.max()

90

In [31]:
# 2
kor[kor >= 80]

array([90])

In [35]:
# 3
kor[(50 <= kor) & (kor<= 80)]

array([60, 55, 70])

In [23]:
# 4
kor.mean()

54.166666666666664

In [24]:
# 5
kor.sum()

325