In [1]:
import numpy as np

용어정리
- scalar : 상수값( 10, 3.14, 'abc')
- vector(1차원): [10, 20, 30 ] , ['ab', 'cd', 'ef'], [3.14, 2.5 ]
- matrix(2차원): [ [10, 20, 30 ],[40, 50, 60 ] ]  2x3
- 3d(3차원):[ [ [10, 20, 30 ],[40, 50, 60 ] ], [ [10, 20, 30 ],[40, 50, 60 ] ] ] 2x2x3


## 객체: 속성, 메소드

### 객체.속성

#### 객체.메소드()

In [ ]:
4차산업혁명
- 사문인터넷: 센서, 네트워크
- 인공지능

In [3]:
myList = [10,20,30]
print(myList)
print(type(myList))

[10, 20, 30]
<class 'list'>


## 1. 리스트 --> ndarray 로 변환

In [3]:
# np.array(myList)
arr1 = np.array([10,20,30])
print(arr1)
print(type(arr1))
arr1

[10 20 30]
<class 'numpy.ndarray'>


array([10, 20, 30])

In [4]:
arr2 = np.array( [ [10, 20, 30 ],[40, 50, 60 ] ] )
print( arr2 )
arr2


[[10 20 30]
 [40 50 60]]


array([[10, 20, 30],
       [40, 50, 60]])

## 2. arange 함수를 이용하여 연속된 ndarray 생성

In [5]:
# np.arange(시작값, 끝값, 증가치) 시작값 <= arr < 끝값
arr3 = np.arange(1,5,1) # 1 <= arr < 5
arr3

array([1, 2, 3, 4])

In [6]:
arr4 = np.arange(1,10,2) # 1 <= arr < 10
arr4

array([1, 3, 5, 7, 9])

## 3. 랜덤 : random 모듈 이용

In [10]:
np.random.seed(5) # 동일한 seed값을 주면 동일한 랜덤값이 나옴. 
arr5 = np.random.randint(1,10, size=5) # 1 <= random <10
arr5

array([4, 7, 7, 1, 9])

In [11]:
arr6 = np.random.randint(1,10,size=(2,3)) # 1 <= random <10
arr6 # 2행 3열짜리

array([[5, 8, 1],
       [1, 8, 2]])

In [12]:
arr7 = np.random.rand(5) # 0~1 사이 실수값을 랜덤으로 
arr7

array([0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703])

In [13]:
arr8 = np.random.rand(5,2) # 0~1 사이 실수값을 랜덤으로 
arr8 # 5행 2열짜리

array([[0.27408646, 0.41423502],
       [0.29607993, 0.62878791],
       [0.57983781, 0.5999292 ],
       [0.26581912, 0.28468588],
       [0.25358821, 0.32756395]])

In [14]:
arr9 = np.random.randn(5) # 표준정규분포 (평균: 0, 편차: 1)
arr9 # 값이 많을수록 평균:0, 편차:1 에 가까워짐

array([-0.21077965, -0.22429966,  0.65122845, -0.96276198,  2.23874294])

In [15]:
arr10 = np.random.randn(5,3) # 표준정규분포 (평균: 0, 편차: 1)
arr10 # 5행 3열짜리

array([[ 0.24778538,  0.32639613,  0.26650019],
       [ 0.37746398, -0.02392064,  1.22888408],
       [-0.39583126,  1.52502591,  0.26157022],
       [-0.4875009 , -0.01560054,  1.13366694],
       [ 0.47173221,  1.96863378,  0.96110296]])

In [21]:
arr11 = np.random.choice([1,2,3,4,5],size=3) # 리스트에서 3개 복원추출(같은 개체가 중복될 수 있음)
arr11

array([1, 1, 3])

In [22]:
arr12 = np.random.choice(np.arange(1,11),size=3,replace=False) # 리스트에서 3개 비복원추출(중복추출X)
arr12

array([6, 8, 9])

In [2]:
my = np.array([1,2,3,4,5])
np.random.shuffle(my)
my  # 임의로 랜덤하게 배치

array([3, 5, 1, 4, 2])

## 4. 타입별 ndarray 만들기

In [4]:
arr13 = np.int32([1,2,3,4,5]) # 개체 하나당 4bytes씩/ 디폴트값은 타입에 맞춰 알아서 결정
# np.array([1,2,3,4,5], dtype=np.int32)
arr13

array([1, 2, 3, 4, 5])

In [5]:
# np.array([1,2,3,4,5], dtype=np.int64)
arr14 = np.int64([1,2,3,4,5])
arr14

array([1, 2, 3, 4, 5], dtype=int64)

In [6]:
# np.array([1,2,3,4,5], dtype=np.float32)# 개체 하나당 4bytes씩
arr15 = np.float32([1,2,3,4,5])
arr15

array([1., 2., 3., 4., 5.], dtype=float32)

In [7]:
arr16 = np.array([1,2,3,4,5], dtype=np.str_) # 문자열 타입으로 만들기
arr16

array(['1', '2', '3', '4', '5'], dtype='<U1')

## 5. 기타 nparray 만들기

In [8]:
arr17 = np.ones(3) # 1로만 구성된 array
arr17

array([1., 1., 1.])

In [10]:
arr18 = np.ones((3,2)) # 1로만 3행 2열짜리 
arr18

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
arr19 = np.zeros((3,2))  # 0으로만 3행 2열짜리
arr19

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
arr20 = np.eye(3) # 희소행렬( one hot encoding.)
arr20 # 대각선으로만 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.linspace(1,10) # start =1, end =10 50개

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [15]:
np.linspace(1,10,num =3) # start =1, end =10 3개

array([ 1. ,  5.5, 10. ])

In [16]:
np.linspace(1,10,num =10) # start =1, end =10 10개

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
arr21 = np.unique([1,2,2,3,3,3,4,5])  # 중복 없이 하나씩만
arr21

array([1, 2, 3, 4, 5])

In [20]:
v,c = np.unique([1,2,2,3,3,3,4,5], return_counts=True)
print(v) # 중복 없이 하나씩만
print(c) # 몇번 중복되었나

[1 2 3 4 5]
[1 2 3 1 1]


In [21]:
for n in zip(v,c):
    print(n)

(1, 1)
(2, 2)
(3, 3)
(4, 1)
(5, 1)


In [22]:
for a,b in zip(v,c):
    print(a,b)

1 1
2 2
3 3
4 1
5 1
