# 선형대수

In [1]:
import numpy as np

In [ ]:
# 넘파이 배열의 특징
# n*m 으로 구성
# 자료형이 같아야 한다.
# ndarray
# https://numpy.org

In [2]:
# 넘파이배열명 = np.array(1차원리스트)
# 넘파이배열명 = np.array(2차원리스트)
arr1 = np.array([1,34,55,67,23]) # 1차원
arr2 = np.array([[1,34],[67,23]]) # 2차원
print(arr1)
print()
print(arr2)

[ 1 34 55 67 23]

[[ 1 34]
 [67 23]]


In [4]:
arr1, type(arr1)

(array([ 1, 34, 55, 67, 23]), numpy.ndarray)

In [5]:
# ndim => 차원
# shape => 구조
arr1.ndim, arr1.shape

(1, (5,))

In [6]:
arr2.ndim, arr2.shape

(2, (2, 2))

In [7]:
# 3행 1열 
arr3 = np.array([[45], [67], [78]])
arr3.ndim, arr3.shape

(2, (3, 1))

In [8]:
# 1차원 => 2차원 
# 넘파이배열.reshape(row, column)
np.array([10, 20, 30, 40, 50, 60]).reshape(2,3)


array([[10, 20, 30],
       [40, 50, 60]])

In [9]:
np.array([10, 20, 30, 40, 50, 60]).reshape(3,2)


array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
# 연속적인 숫자로 구성된 넘파이 배열 
# np.arange(start, end, step)
# np.arange(start, end, step).reshape(n,m)


In [10]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
np.arange(0,51,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [13]:
len(np.arange(0,51,2).reshape(13,2))

13

In [14]:
np.arange(0,51,2).reshape(13,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38],
       [40, 42],
       [44, 46],
       [48, 50]])

In [15]:
np.array([[5,2,2], [1,7,3]])

array([[5, 2, 2],
       [1, 7, 3]])

### 전치행렬
- 행과 열을 변경
- 2행3열 => 3행2열
- 넘파이배열.T

In [16]:
arr = np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
# 0 으로 구성된 넘파이 배열
np.zeros(9, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.zeros(9, dtype=int).reshape(3,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
# 1로 구성된 넘파이 배열
np.ones(9, dtype=int).reshape(3,3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [22]:
# 리스트 연산( + : 연결)
list_a = list(range(1,6))
list_b = list(range(11,16))
print(list_a)
print(list_b)

[1, 2, 3, 4, 5]
[11, 12, 13, 14, 15]


In [23]:
print(list_a + list_b)

[1, 2, 3, 4, 5, 11, 12, 13, 14, 15]


In [25]:
# print(list_a - list_b) #TypeError

In [26]:
# 리스트 * 양의정수
# 리스트의 반복
list_a*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [27]:
# 넘파이 배열의 연산
# 각 위치를 기준으로 성분끼리 연산
arr_a = np.arange(1,6)
arr_b = np.arange(11, 16)
print(arr_a)
print()
print(arr_b)

[1 2 3 4 5]

[11 12 13 14 15]


In [28]:
arr_a + arr_b

array([12, 14, 16, 18, 20])

In [29]:
arr_a - arr_b

array([-10, -10, -10, -10, -10])

In [30]:
# 정수곱
arr_a * 5 

array([ 5, 10, 15, 20, 25])

In [33]:
#  항등 넘파이 배열
# np.identity(n) : n은 1의 갯수 
np.identity(3, dtype=int)


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
# 쥬피터노트북에서 제공하는 레퍼런스 활용
# 명령어?
np.identity?

# dot.product
- 대상이 되는 배열의 관계
- n행m열 => m행n열

In [34]:
arr1 = np.array([6,6])
arr2 = np.array([12,0])
print(arr1)
print()
print(arr2)

[6 6]

[12  0]


In [35]:
# 2행 3열
arr1 = np.arange(1,7).reshape(2,3)
# 3행 2열 
arr2 = np.arange(11,17).reshape(3,2)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr2

array([[11, 12],
       [13, 14],
       [15, 16]])

In [37]:
# 행렬의 곱셈
np.dot(arr1,arr2)

array([[ 82,  88],
       [199, 214]])