In [2]:
import numpy as np

In [3]:
data = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [4]:
data.shape  #4행3열

(4, 3)

In [5]:
data.reshape(2,6) # 재배열 2행 6열, 데이터 12개가 배열가능한 경우의 수만 가능.

array([[ 1,  2,  3,  7,  5,  2],
       [10,  1,  8,  6,  3,  4]])

In [8]:
data.reshape(-1,6)  # -1은 6열에 맞춰 자동으로 행을 지정하라는 뜻
data.reshape(-1,4)  # -1은 4열에 맞춰 자동으로 행을 지정하라는 뜻
data.reshape(6,-1)  # -1은 6행에 맞춰 자동으로 열을 지정하라는 뜻

array([[ 1,  2],
       [ 3,  7],
       [ 5,  2],
       [10,  1],
       [ 8,  6],
       [ 3,  4]])

In [9]:
data.reshape(2,2,3)  #2행 3열 2개

array([[[ 1,  2,  3],
        [ 7,  5,  2]],

       [[10,  1,  8],
        [ 6,  3,  4]]])

In [10]:
data.reshape(-1,2,3)  # 행은 3열에 맞춰 자동 결정. 2개 생성

array([[[ 1,  2,  3],
        [ 7,  5,  2]],

       [[10,  1,  8],
        [ 6,  3,  4]]])

## 인덱싱
- 2차원: [행,열]
- 3차원: [면,행,열]
- ,(콤마)로 구분


In [11]:
data = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [12]:
data[0] # 0번째 행

array([1, 2, 3])

In [13]:
data[0,0] # 0행 0열

1

In [14]:
data[[0,2,3]] # 0행 2행 3행 (복수개 선택)

array([[ 1,  2,  3],
       [10,  1,  8],
       [ 6,  3,  4]])

In [16]:
data[1,[1,2]] # 복수개 컬럼(열) 선택

array([5, 2])

## boolean 인덱싱(행단위)

In [17]:
data = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [18]:
data[[True,False,True,True]] # 4행중에 true인 행만 출력

array([[ 1,  2,  3],
       [10,  1,  8],
       [ 6,  3,  4]])

## 슬라이싱(slicing)

In [19]:
data = np.array( [ [1,2,3],[7,5,2],[10,1,8],[6,3,4] ] )
data

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [20]:
data[1:3] # 1 <= 행인덱스 < 3

array([[ 7,  5,  2],
       [10,  1,  8]])

In [21]:
data[1:] # 1행부터 끝까지

array([[ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [22]:
data[:] # 0행부터 끝까지(전체)

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [23]:
data[:,1] # 인덱스 1인 열 (1차원)

array([2, 5, 1, 3])

In [ ]:
data[:,[1]] # 복수개 선택이라 행렬이 유지되어 출력(2차원)

In [24]:
data[:,[1,2]] # 인덱스가 각각 1,2 인 열

array([[2, 3],
       [5, 2],
       [1, 8],
       [3, 4]])

In [25]:
data[:,1:] # 인덱스 1인 열부터 끝까지

array([[2, 3],
       [5, 2],
       [1, 8],
       [3, 4]])

In [26]:
data[1:3,[0,2]]

array([[ 7,  2],
       [10,  8]])

In [30]:
data[1:3,[0]], data[1:3,[2]]

(array([[ 7],
        [10]]),
 array([[2],
        [8]]))

In [31]:
data[1:3,::2]

array([[ 7,  2],
       [10,  8]])

In [32]:
# 맨 마지막 컬럼을 제외하고 선택하시오.
data[:,:-1]

array([[ 1,  2],
       [ 7,  5],
       [10,  1],
       [ 6,  3]])

In [33]:
# 맨 마지막 컬럼을 선택하시오(결과는 matrix로).
data[:,[-1]]

array([[3],
       [2],
       [8],
       [4]])